spring:
  application.name: routine-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:55432/routine_service}
    username: ${SPRING_DATASOURCE_USERNAME:routine_service}
    password: ${SPRING_DATASOURCE_PASSWORD:routine_service_pw}
  flyway:
    locations: classpath:db/migration
    clean-disabled: true
    create-schemas: true
    default-schema: routine
    schemas: routine
  jackson.deserialization.fail-on-unknown-properties: true
server:
  port: ${PORT:8080}
  address: ${SERVER_ADDRESS:0.0.0.0}
management.endpoints.web.exposure.include: health,info
routine.exercise-service-base-url: ${EXERCISE_SERVICE_BASE_URL:http://127.0.0.1:8090}
