spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:55432/fitness}
    username: ${SPRING_DATASOURCE_USERNAME:routine_service}
    password: ${SPRING_DATASOURCE_PASSWORD:routine_service_pw}
  docker:
    compose:
      enabled: false
